theme: jekyll-theme-minimal
title: Raphael Mignot
description: PhD Student in Statistics and Machine Learning at Université de Lorraine.
logo: /assets/img/logo.png
email: first name dot last name at univ-lorraine dot fr
show_downloads: false
github: [metadata]
