theme: jekyll-theme-minimal
title: Raphael Mignot
description: PhD Student in Statistics and Machine Learning at Université de Lorraine.
logo: /assets/img/profile-pic-600x600.png
show_downloads: false
